baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Equipa'
    pageRef = '/equipa'
    weight = 20

  [[menus.main]]
    name = 'Agenda'
    pageRef = '/agenda'
    weight = 20

  [[menus.main]]
    name = "Orquestra d'aquem Mar"
    identifier = 'orq'
    pageRef = '/orquestra'
    weight = 20

  [[menus.main]]
    name = "Sons d'aquem Mar"
    parent = 'orq'
    pageRef = '/sons'
    weight = 20

  [[menus.main]]
    name = 'Eventos'
    identifier = 'eventos'
    pageRef = '/eventos'

  [[menus.main]]
    name = 'Criação Artistica'
    parent = 'eventos'
    pageRef = '/eventos/artistica'

  [[menus.main]]
    name = 'Criação Participativa'
    parent = 'eventos'
    pageRef = '/eventos/participativa'

  [[menus.main]]
    name = 'Artes Visuais'
    parent = 'eventos'
    pageRef = '/eventos/artesvisuais'


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[params]
  facebook = 'https://facebook.com/questao.repetida'
  instagram = 'https://instagram.com/questao.repetida'
  whatsapp = 'https://wa.me/351932399639'

[security]
  enableInlineShortcodes = true

[markup.goldmark.parser.attribute]
  block = true

